db:
  url: jdbc:mysql://192.168.16.101:3306/vito_bank?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
  username: root
  password: 12345678
  driver: com.mysql.cj.jdbc.Driver